# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.0.4.dev132+gc3c0a57f.d20201215'
version_tuple = (0, 0, 4, 'dev132+gc3c0a57f', 'd20201215')
