# version info for downloading source code
{% set pypi_url = environ.get('PYPI_URL', "https://artifactory.ihme.washington.edu/artifactory/api/pypi/pypi-shared") %}
{% set version = environ.get('CONDA_CLIENT_VERSION', 1.0) %}
{% set jobmon_version = environ.get('JOBMON_VERSION', "2.2.2.dev448") %}
{% set jobmon_uge_version = environ.get('JOBMON_UGE_VERSION', "0.1.dev53") %}
{% set jobmon_slurm_version = environ.get('JOBMON_SLURM_VERSION', "0.1.dev56") %}

# import setup.py info
{% set jobmon_setup = load_setup_py_data(setup_file="jobmon/setup.py") %}
{% set jobmon_uge_setup = load_setup_py_data(setup_file="jobmon_uge/setup.py") %}
{% set jobmon_slurm_setup = load_setup_py_data(setup_file="jobmon_slurm/setup.py") %}

package:
  name: ihme_jobmon
  version: {{ version }}

source:
  # wheels for install
  - url: {{ pypi_url }}/jobmon-uge/{{ jobmon_uge_version }}/jobmon_uge-{{ jobmon_uge_version }}-py3-none-any.whl
    folder: wheels
  - url: {{ pypi_url }}/jobmon-slurm/{{ jobmon_slurm_version }}/jobmon_slurm-{{ jobmon_slurm_version }}-py3-none-any.whl
    folder: wheels
  - url: {{ pypi_url }}/jobmon/{{ jobmon_version }}/jobmon-{{ jobmon_version }}-py3-none-any.whl
    folder: wheels
  # # tarballs for dependencies
  - url: {{ pypi_url }}/jobmon-uge/{{ jobmon_uge_version }}/jobmon_uge-{{ jobmon_uge_version }}.tar.gz
    folder: jobmon_uge
  - url: {{ pypi_url }}/jobmon-slurm/{{ jobmon_slurm_version }}/jobmon_slurm-{{ jobmon_slurm_version }}.tar.gz
    folder: jobmon_slurm
  # - path: ../../../
  - url: {{ pypi_url }}/jobmon/{{ jobmon_version }}/jobmon-{{ jobmon_version }}.tar.gz
    folder: jobmon

build:
  noarch: python
  number: {{ environ.get('JENKINS_BUILD_NUMBER', 0) }}
  script_env:
   - WEB_SERVICE_FQDN
   - WEB_SERVICE_PORT

requirements:
  host:
    - python
    - pip
    - configargparse
    - pandas
    - requests
    - tenacity
  run:
  {% for req in jobmon_setup.get('install_requires', []) %}
    - {{ req|replace("_", "-") }}
  {% endfor %}
  {% for req in jobmon_uge_setup.get('install_requires', []) %}
  {% if req != 'jobmon' -%}
    - {{ req|replace("_", "-") }}
  {%- endif %}
  {% endfor %}
test:
  imports:
    - jobmon
    - jobmon_uge
    - jobmon_slurm

about:
  home: https://scicomp-docs.ihme.washington.edu/jobmon/{{ jobmon_version }}
  summary: {{ jobmon_setup['description'] }}
