version: '3'

services:
  jsm:
    build: .
    image: jobmon
    volumes:
        - ./jsm_uwsgi.ini:/app/uwsgi.ini
    ports:
        - "7256:80"
    entrypoint:
        - ./wait-for-tables.sh
        - db
    environment:
        - JOBMON_PASS_SERVICE_USER
        - CONN_STR=${SERVICE_USER_CONN_STR}
    command: [
        "jobmon",
        "--verbose",
        "start", "job_state_manager"]
    links:
        - db
    logging:
        options:
            max-size: "100m"
            max-file: "10"
  jqs:
    image: jobmon
    volumes:
        - ./jqs_uwsgi.ini:/app/uwsgi.ini
    ports:
        - "7258:80"
    entrypoint:
        - ./wait-for-tables.sh
        - db
    environment:
        - JOBMON_PASS_SERVICE_USER
        - CONN_STR=${SERVICE_USER_CONN_STR}
    command: [
        "jobmon",
        "--verbose",
        "start", "job_query_server"]
    links:
        - db
    logging:
        options:
            max-size: "100m"
            max-file: "10"
  monitor:
    image: jobmon
    depends_on:
        - jsm
    entrypoint:
        - ./wait-for-tables.sh
        - db
    environment:
        - JOBMON_PASS_SERVICE_USER
        - CONN_STR=${SERVICE_USER_CONN_STR}
    command: [
        "jobmon",
        "--verbose",
        "start", "health_monitor"]
    links:
        - db
        - jsm
    logging:
        options:
            max-size: "100m"
            max-file: "10"
  initdb:
    image: jobmon
    depends_on:
        - jsm
    entrypoint:
        - ./wait-for-db.sh
        - db
    environment:
        - JOBMON_PASS_TABLE_CREATOR
        - CONN_STR=${TABLE_CREATOR_CONN_STR}
    command: ["jobmon", "--verbose", "initdb"]
    links:
        - db
    volumes:
        - ./jobmonrc-docker-initdb:/root/.jobmonrc
  db:
    image: mysql:5.7
    ports:
        - "3317:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=${JOBMON_PASS_ROOT}
        - MYSQL_DATABASE=docker
        - JOBMON_PASS_ROOT
        - JOBMON_PASS_TABLE_CREATOR
        - JOBMON_PASS_SERVICE_USER
        - JOBMON_PASS_READ_ONLY

    volumes:
        - mysql-jobmon-emu:/var/lib/mysql
        - ./create_users.sh:/docker-entrypoint-initdb.d/create_users.sh

volumes:
    mysql-jobmon-emu: {}
