version: '3'

services:
  jsm:
    build: .
    image: jobmon
    ports:
        - "5156:3456"
        - "5157:3457"

    entrypoint:
        - ./wait-for-tables.sh
        - db
    command: [
        "jobmon",
        "--verbose",
        "start", "job_state_manager"]
    links:
        - db
    logging:
        options:
            max-size: "100m"
            max-file: "10"
  jqs:
    image: jobmon
    depends_on:
        - jsm
    ports:
        - "5158:3458"
    entrypoint:
        - ./wait-for-tables.sh
        - db
    command: [
        "jobmon",
        "--verbose",
        "start", "job_query_server"]
    links:
        - db
    logging:
        options:
            max-size: "100m"
            max-file: "10"
  monitor:
    image: jobmon
    depends_on:
        - jsm
    entrypoint:
        - ./wait-for-tables.sh
        - db
    command: [
        "jobmon",
        "--verbose",
        "start", "health_monitor"]
    links:
        - db
        - jsm
    logging:
        options:
            max-size: "100m"
            max-file: "10"
  initdb:
    image: jobmon
    depends_on:
        - jsm
    entrypoint:
        - ./wait-for-db.sh
        - db
    command: ["jobmon", "--verbose", "initdb"]
    links:
        - db
  db:
    image: mysql
    ports:
        - "3313:3306"
    environment:
        MYSQL_ROOT_PASSWORD: docker
        MYSQL_DATABASE: docker
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
    volumes:
        - mysql-jobmon-emu:/var/lib/mysql

volumes:
    mysql-jobmon-emu: {}
