version: '2'

services:
  monitor:
    image: jobmon
    ports:
        - "5555:5000"
        - "5556:3456"
    command: [
        "./wait-for-db.sh", "db", "python", "bin/launch_central_monitor.py",
        "--dir_path", "/app",
        "--mon_port", "5000",
        "--pub_port", "3456",
        "--conn_str", "mysql://docker:docker@db/docker"]
    links:
        - db
    logging:
        options:
            max-size: "100m"
            max-file: "10"

  db:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: docker
        MYSQL_DATABASE: docker
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
    volumes:
        - mysql-jobmon:/var/lib/mysql

volumes:
    mysql-jobmon: {}
