version: '3'

services:
  jsm:
    build: .
    image: jobmon
    ports:
        - "4656:3456"
        - "4657:3457"

    entrypoint:
        - ./wait-for-db.sh
        - db
    command: [
        "jobmon",
        "--verbose",
        "start", "job_state_manager"]
    links:
        - db
    logging:
        options:
            max-size: "100m"
            max-file: "10"
  jqs:
    image: jobmon
    ports:
        - "4658:3458"
    entrypoint:
        - ./wait-for-db.sh
        - db
    command: [
        "jobmon",
        "--verbose",
        "start", "job_query_server"]
    links:
        - db
    logging:
        options:
            max-size: "100m"
            max-file: "10"
  initdb:
    image: jobmon
    entrypoint:
        - ./wait-for-db.sh
        - db
    command: ["jobmon", "--verbose", "initdb"]
    links:
        - db
  db:
    image: mysql
    ports:
        - "3308:3306"
    environment:
        MYSQL_ROOT_PASSWORD: docker
        MYSQL_DATABASE: docker
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
    volumes:
        - mysql-jobmon-emu:/var/lib/mysql

volumes:
    mysql-jobmon-emu: {}
