version: '2'

services:
  monitor:
    image: jobmon
    ports:
        - "5555:5000"
    command: ["./wait-for-db.sh", "db", "python", "bin/launch_central_monitor.py", "/app",
              "5000", "--conn_str", "mysql://DB_USERNAME:DB_PASSWORD@internal-db-p02.ihme.washington.edu/jobmon"]
    links:
        - db
    logging:
        options:
            max-size: "100m"
            max-file: "10"

  db:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: docker
        MYSQL_DATABASE: docker
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
    volumes:
        - mysql-jobmon:/var/lib/mysql

volumes:
    mysql-jobmon: {}
