version: '3'

services:
  jobmon:
    build: .
    image: jobmon
    volumes:
        - ./uwsgi.ini:/app/uwsgi.ini
    ports:
        - "${EXTERNAL_SERVICE_PORT}:80"
    entrypoint:
        - ./wait-for-tables.sh
        - db
    command: ["jobmon", "start", "web_service"]
    environment:
        - DB_HOST=${INTERNAL_DB_HOST}
        - DB_PORT=${INTERNAL_DB_PORT}
        - DB_USER=service_user
        - DB_PASS=${JOBMON_PASS_SERVICE_USER}
        - JOBMON_PORT=${EXTERNAL_SERVICE_PORT}
    links:
        - db
    logging:
        options:
            max-size: "100m"
            max-file: "10"
  monitor:
    image: jobmon
    depends_on:
        - jobmon
    entrypoint:
        - ./wait-for-tables.sh
        - db
    environment:
        - DB_HOST=${INTERNAL_DB_HOST}
        - DB_PORT=${INTERNAL_DB_PORT}
        - DB_USER=service_user
        - DB_PASS=${JOBMON_PASS_SERVICE_USER}
        - JOBMON_PORT=${EXTERNAL_SERVICE_PORT}
    links:
    command: ["jobmon", "start", "health_monitor"]
    links:
        - db
        - jobmon
    logging:
        options:
            max-size: "100m"
            max-file: "10"
  initdb:
    image: jobmon
    depends_on:
        - jobmon
    entrypoint:
        - ./wait-for-db.sh
        - db
    environment:
        - DB_HOST=${INTERNAL_DB_HOST}
        - DB_PORT=${INTERNAL_DB_PORT}
        - DB_USER=table_creator
        - DB_PASS=${JOBMON_PASS_TABLE_CREATOR}
        - JOBMON_PORT=${EXTERNAL_SERVICE_PORT}
    command: ["jobmon", "initdb"]
    links:
        - db
  db:
    image: mysql:5.7
    ports:
        - "${EXTERNAL_DB_PORT}:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=${JOBMON_PASS_ROOT}
        - MYSQL_DATABASE=docker
        - JOBMON_PASS_ROOT
        - JOBMON_PASS_TABLE_CREATOR
        - JOBMON_PASS_SERVICE_USER
        - JOBMON_PASS_READ_ONLY

    volumes:
        - mysql-jobmon-emu:/var/lib/mysql
        - ./create_users.sh:/docker-entrypoint-initdb.d/create_users.sh

volumes:
    mysql-jobmon-emu: {}
