version: '3'

services:
  monitor:
    build: .
    volumes:
        - .:/app
    image: jobmon
    ports:
        - "3456:3456"
        - "3457:3457"

    entrypoint:
        - ./wait-for-db.sh
        - db
    command: [
        "python", "/app/jobmon/cli.py",
        "--state_manager_reply_port", "3456",
        "--state_manager_publish_port", "3457",
        "--verbose"]
    links:
        - db
    logging:
        options:
            max-size: "100m"
            max-file: "10"

  db:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: docker
        MYSQL_DATABASE: docker
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
    volumes:
        - mysql-jobmon:/var/lib/mysql

volumes:
    mysql-jobmon: {}
