version: '2'

services:
  monitor:
    image: jobmon
    ports:
        - "5000:5000"
    command: ["./wait-for-db.sh", "db", "flask", "run", "--host=0.0.0.0"]
    links:
        - db
    environment:
        - FLASK_APP=jobmon/app.py
        - FLASK_DEBUG=1
        - LC_ALL=C.UTF-8
        - LANG=C.UTF-8
    volumes:
        - ./:/app

  db:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: docker
        MYSQL_DATABASE: docker
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
    volumes:
        - mysql-jobmon:/var/lib/mysql

volumes:
    mysql-jobmon: {}
