version: "3.9"
services:
  jobmon_backend:
    build: 
      context: ./
      dockerfile: ./jobmon_server/Dockerfile
      args:
        EDITABLE: "${EDITABLE:-false}"  # Pass the EDITABLE argument with a default of false
        EXTRAS: "${EXTRAS:-}"          # Pass the EXTRAS argument with a default of empty
    ports:
      - "8070:80"
    volumes:
      - ./jobmon_core:/app/jobmon/jobmon_core:ro
      - ./jobmon_server:/app/jobmon/jobmon_server:ro
    env_file:
      - .env
    command: >
      /bin/sh -c "jobmon_server init_db && fastapi run /app/main.py --port 80 --reload"
  jobmon_frontend:
    build: 
      context: ./jobmon_gui
      dockerfile: ./Dockerfile.local
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - ./jobmon_gui/src:/app/src:ro
    env_file:
      - .env  # Load environment variables from the .env file
