apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: monitor
  name: monitor
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: monitor
    spec:
      containers:
      - args:
        - jobmon
        - --verbose
        - start
        - workflow_reaper
        command:
        - ./wait-for-tables.sh
        - db
        image: myjobmonregistry.azurecr.io/jobmon
        name: monitor
        imagePullPolicy: IfNotPresent
        resources: {}
      restartPolicy: Always
status: {}
