"""empty message

Revision ID: a22651d2d11a
Revises: 
Create Date: 2017-05-25 12:13:34.306681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22651d2d11a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('user', sa.String(length=150), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.add_column('job', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job', 'batch', ['batch_id'], ['batch_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_column('job', 'batch_id')
    op.drop_table('batch')
    # ### end Alembic commands ###
