---
kind: Deployment
apiVersion: apps/v1
metadata:
  # Resource policy keeps old reapers in the namespace when deploying new ones
  annotations:
    "helm.sh/resource-policy": keep
  name: jobmon-reaper-{{ .Values.global.jobmon_version }}
  namespace: jobmon-reapers
  labels:
    app: jobmon-reaper-{{ .Values.global.jobmon_version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobmon-reaper-{{ .Values.global.jobmon_version }}
  template:
    metadata:
      labels:
        app: jobmon-reaper-{{ .Values.global.jobmon_version }}
        name: jobmon-reaper-{{ .Values.global.jobmon_version }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: {{ .Values.global.jobmon_container_uri }}
        imagePullPolicy: Always
        name: jobmon-workflow-reaper
        command: ["jobmon_server"]
        args: ["workflow_reaper", "start"]
        env:
        - name: SLACK_API_URL
          valueFrom:
            secretKeyRef:
              key: SLACK_API_URL
              name: {{ .Values.global.rancher_slack_secret }}
        - name: SLACK_CHANNEL_DEFAULT
          valueFrom:
            secretKeyRef:
              key: SLACK_CHANNEL_DEFAULT
              name: {{ .Values.global.rancher_slack_secret }}
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              key: SLACK_TOKEN
              name: {{ .Values.global.rancher_slack_secret }}
        - name: WEB_SERVICE_FQDN
          value: "traefik-{{ .Values.global.namespace }}"
        - name: WEB_SERVICE_PORT
          value: "80"
        resources:
          limits:
            memory: 400Mi
            cpu: 300m
          requests:
            cpu: 100m # m = mhz
            memory: 200Mi
---
# Connect to the traefik controller in the target namespace
kind: Service
apiVersion: v1
metadata:
  name: traefik-{{ .Values.global.namespace }}
  namespace: {{ .Values.global.reaper_namespace }}
spec:
  type: ExternalName
  externalName: traefik.{{ .Values.global.namespace }}.svc.cluster.local
  ports:
  - port: 80
