---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jobmon-integration
  namespace: {{ .Values.global.namespace }}
  labels:
    app: jobmon-integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobmon-integration
  template:
    metadata:
      labels:
        app: jobmon-integration
        name: jobmon-integration
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: {{ .Values.global.jobmon_container_uri }}
        imagePullPolicy: Always
        name: jobmon-integration
        command: ["jobmon_server"]
        args: ["integration", "start"]
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: {{ .Values.global.rancher_db_secret }}
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: DB_PORT
              name: {{ .Values.global.rancher_db_secret }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: DB_USER
              name: {{ .Values.global.rancher_db_secret }}
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: DB_PASS
              name: {{ .Values.global.rancher_db_secret }}
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: DB_NAME
              name: {{ .Values.global.rancher_db_secret }}
        - name: DB_HOST_SLURM_SDB
          valueFrom:
            secretKeyRef:
              key: DB_HOST_SLURM_SDB
              name: {{ .Values.global.rancher_db_slurm_sdb_secret }}
        - name: DB_PORT_SLURM_SDB
          valueFrom:
            secretKeyRef:
              key: DB_PORT_SLURM_SDB
              name: {{ .Values.global.rancher_db_slurm_sdb_secret }}
        - name: DB_USER_SLURM_SDB
          valueFrom:
            secretKeyRef:
              key: DB_USER_SLURM_SDB
              name: {{ .Values.global.rancher_db_slurm_sdb_secret }}
        - name: DB_PASS_SLURM_SDB
          valueFrom:
            secretKeyRef:
              key: DB_PASS_SLURM_SDB
              name: {{ .Values.global.rancher_db_slurm_sdb_secret }}
        - name: DB_NAME_SLURM_SDB
          valueFrom:
            secretKeyRef:
              key: DB_NAME_SLURM_SDB
              name: {{ .Values.global.rancher_db_slurm_sdb_secret }}
        - name: INTEGRATOR_RETIRE_AGE
          value: {{ .Values.global.rancher_retire_age | quote }}

        resources:
          limits:
            memory: 2400Mi
            cpu: 1200m
          requests:
            cpu: 1000m # m = mhz
            memory: 1200Mi