# Kubernetes namespace creation, only run if it doesn't exist
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: {{ .Values.global.namespace }}
  name: {{ .Values.global.namespace }}
  annotations:
    field.cattle.io/projectId: {{ .Values.global.rancher_project }}

---
# Links the traefik-ingress-controller cluster role to the service account. This will grant the
# service account permissions to cluster-wide secrets. Only create the ClusterRoleBinding if
# creating a new namespace.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller-{{ .Values.global.namespace }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: {{ .Values.global.namespace }}