# jobmon_client cluster IP. Used for communication between k8s deployments.
# Eg traefik -> jobmon-server
# Allows hostname "jobmon-server" to resolve inside k8s containers
---
apiVersion: v1
kind: Service
metadata:
  name: jobmon-server
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: jobmon-server
