# jobmon_client cluster IP. Used for communication between k8s deployments.
# Eg traefik -> jobmon-server
# Allows hostname "jobmon-server" to resolve inside k8s containers
---
apiVersion: v1
kind: Service
metadata:
  name: jobmon-server
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: jobmon-server

# Logstash cluster IP, endpoint for Jobmon service logs
# Allows hostname "logstash" to resolve inside Jobmon containers
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  type: ClusterIP
  ports:
    - protocol: UDP
      name: logstash
      port: 5000
  selector:
    app: logstash

# Elasticsearch cluster IP, endpoint for logstash and source for Kibana
# Allows hostname "elasticsearch" to resolve inside ELK containers
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: elasticsearch
      port: 9200
  selector:
    app: elasticsearch

# Kibana cluster IP
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: kibana
      port: 5601
  selector:
    app: kibana

# APM cluster IP
---
apiVersion: v1
kind: Service
metadata:
  name: jobmon-apm
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: jobmon-apm
      port: 8200
  selector:
    app: jobmon-apm
