---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jobmon-server
  namespace: {{ .Values.global.namespace }}
  labels:
    app: jobmon-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobmon-server
  template:
    metadata:
      labels:
        app: jobmon-server
        name: jobmon-server
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: {{ .Values.global.jobmon_container_uri }}
        imagePullPolicy: Always
        name: jobmon-server
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: {{ .Values.global.rancher_db_secret }}
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: DB_PORT
              name: {{ .Values.global.rancher_db_secret }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: DB_USER
              name: {{ .Values.global.rancher_db_secret }}
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: DB_PASS
              name: {{ .Values.global.rancher_db_secret }}
        envFrom:
        - configMapRef:
            name: jobmon-config
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            memory: 1000Mi # 1000Mi = 1G
            cpu: 1000m # 1000m = 1000 milli cores = 1 CPU
          requests:
            cpu: 200m
            memory: 500Mi
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "15"]
---
# https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: jobmon-server
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jobmon-server
  maxReplicas: 20
  minReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80


###-----------------How the maxReplicas calculated----------------------------------------------------------------------
###We have 52 cores, and we should leave about 40% to 50% to the hypervisor for stability,
###so that makes it 26 -30. We have 3 applications: jobmon, qpid, and rules,
###and each has services like logstash, grafana...
###The workload metrics shows their are pretty light though, so I assume they take 1 cpu per application.
###That leave jobmon-server about 20 cores. I set the cpu limits to 1000m, which is 1 core/pod max, so the replica is 20.