---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jobmon-squid-integration
  namespace: {{ .Values.global.namespace }}
  labels:
    app: jobmon-squid-integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobmon-squid-integration
  template:
    metadata:
      labels:
        app: jobmon-squid-integration
        name: jobmon-squid-integration
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: {{ .Values.global.jobmon_container_uri }}
        imagePullPolicy: Always
        name: jobmon-squid-integration
        command: ["jobmon_server"]
        args: ["squid_integration", "start"]
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: {{ .Values.global.rancher_db_secret }}
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: DB_PORT
              name: {{ .Values.global.rancher_db_secret }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: DB_USER
              name: {{ .Values.global.rancher_db_secret }}
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: DB_PASS
              name: {{ .Values.global.rancher_db_secret }}
        - name: QPID_URI
          valueFrom:
            secretKeyRef:
              key: QPID_URI
              name: {{ .Values.global.rancher_qpid_secret }}
        resources:
          limits:
            memory: 400Mi
            cpu: 300m
          requests:
            cpu: 100m # m = mhz
            memory: 200Mi
