---
# MetalLB -> traefik ingress
kind: Service
apiVersion: v1
metadata:
  name: traefik
  namespace: {{ .Values.global.namespace }}
  annotations:
    # This is the only connection back to the MetalLB Repo, the value filled in here
    # will determine the IP addresses available to the deployment.
    metallb.universe.tf/address-pool: {{ .Values.global.metallb_ip_pool }}
spec:
  selector:
    app: traefik
  ports:
  - protocol: TCP
    port: 80
    name: web
    nodePort:
  - protocol: TCP
    port: 5601
    name: kibana
    nodePort:
  - protocol: TCP
    port: 9200
    name: elasticsearch
    nodePort:
  - protocol: TCP
    port: 5000
    name: logstash
    nodePort:
  type: LoadBalancer
