# route for jobmon-server
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jobmon-server
  namespace: {{ .Values.global.namespace }}
spec:
  entryPoints:
    # EntryPoints defined in 30_deployment_traefik.yaml.j2 (ports and traefik arguments)
    - web
  routes:
  - match: PathPrefix(`/`)
    kind: Rule
    services:
    - name: jobmon-server
      port: 80

# Grafana routes
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-routes
  namespace: {{ .Values.global.namespace }}
spec:
  entryPoints:
    # EntryPoints defined in 30_deployment_traefik.yaml.j2 (ports and traefik arguments)
    - grafana
  routes:
  - match: PathPrefix(`/`)
    kind: Rule
    services:
    - name: grafana
      port: 3000

# Kibana routes
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kibana-routes
  namespace: {{ .Values.global.namespace }}
spec:
  entryPoints:
    # EntryPoints defined in 30_deployment_traefik.yaml.j2 (ports and traefik arguments)
    - kibana
  routes:
  - match: PathPrefix(`/`)
    kind: Rule
    services:
    - name: kibana
      port: 5601

# Elasticsearch routes
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: elasticsearch-routes
  namespace: {{ .Values.global.namespace }}
spec:
  entryPoints:
    # EntryPoints defined in 30_deployment_traefik.yaml.j2 (ports and traefik arguments)
    - elasticsearch
  routes:
  - match: PathPrefix(`/`)
    kind: Rule
    services:
    - name: elasticsearch
      port: 9200

# logstash routes
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: logstash-routes
  namespace: {{ .Values.global.namespace }}
spec:
  entryPoints:
    # EntryPoints defined in 30_deployment_traefik.yaml.j2 (ports and traefik arguments)
    - logstash
  routes:
  - match: PathPrefix(`/`)
    kind: Rule
    services:
    - name: logstash
      port: 5000