apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
  namespace: {{ .Values.global.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: elasticsearch
  template:
    metadata:
      labels:
        name: elasticsearch
        app: elasticsearch
    spec:
      containers:
        - image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
          name: elasticsearch
          ports:
          - name: http
            containerPort: 9200
          env:
          - name: discovery.type
            value: single-node
          resources:
            limits:
              memory: 1500Mi
              cpu: 2
            requests:
              cpu: 300m
              memory: 900Mi
          volumeMounts:
          - name: elasticsearch-data
            mountPath: /usr/share/elasticsearch/data
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-storage