name: Run CI

on:
  pull_request:
    branches:
      - main
      - 'release/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: Install nox
        run: pip install --upgrade nox
        
      - name: Type checking and Linting
        run: nox -s typecheck lint

      - name: Run tests
        id: tests
        run: nox -s tests -- ./tests/core

      - name: Upload coverage report
        id: coverage
        if: steps.tests.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: htmlcov/*

      - name: Deploy coverage to Github Pages
        if: steps.coverage.outcome == 'success'
        uses: actions/deploy-pages@v2

      - name: Junit Test Dashboard
        if: always() && steps.tests.outcome != 'skipped'
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          path: out/test_report.xml
