name: Build & Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    # Nox probably does what we need
#    strategy:
#      matrix: { products: [ "jobmon-core", "jobmon-server", "jobmon-client" ] }

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build nox
    - name: Build package
      #ToDo Restrict to Jobmon-client?
      run: nox -s build
  publish:
      needs: ['build']
      environment: 'deploy'
      name: upload release to PyPI
      runs-on: ubuntu-latest
      permissions:
        id-token: write
      steps:
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
