name: Build & Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    environment: 'deploy'
    runs-on: ubuntu-latest
    # Advice on security best practice is to have two jobs, one for building and one for deploying to pypi.
    # Only the deploying one has the write permissions. But splitting meant that the second job can't find the
    # dist directory.
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build nox
    - name: Build package
      run: nox -s build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
